### ISSUE TITLE
Some feedback

### ISSUE THREAD

**Issue by cjhoward92** [alexsasharegan/safe-types#1]
Hey man, nice library! I haven't used it in a project yet (although I intend to), but I had a couple of questions.

For one, is it idiomatic TypeScript to use `snake_case` for function names? It doesn't really matter to me but it seems like an interesting decision that I assume comes from Rust.

Secondly, I think it would be useful if `map` and `filter` functions actually ran `map` and `filter` on options if the `Some` value was an array.

You even have the Monad `bind` function, called `and_then` in your code. That's awesome dude. I really like this.

Now that I think about my second point, about `map` and `filter`, ignore that. It doesn't work that way in any other language as `Array` is a functor itself, so you would need `fmap fmap transform array` if, say, your base type was `Maybe Array`.

**Comment by alexsasharegan** [comment]
The snake case is a rust inheritance. I don't think it's idiomatic JS/TS, but frankly I've never cared much. Might be worth a major version bump if that's a common awkwardness.

The map/filter doing double duty sounds like a nice convenience, but I've grown very wary of convenience functions. The concept of map/filter is to transform or apply a predicate to your wrapped type `T`, so doing extra work if that happens to be an array seems use case dependent. I can invision it as a static method helper, but when written out doesn't look really any different that just doing the work explicitly: 

```ts
Option.of(maybeArray).map(Option.mapEach(elem => elem.toLowerCase()));
// vs.
Option.of(maybeArray).map(definitelyArray => definitelyArray.map(elem => elem.toLowerCase()));
```

The `and_then` is surprisingly powerful. I've used this to propagate errors from a whole bunch of async i/o, and you can easily end up with nested results. Running the nested result through `nestedResult.and_then(innerResult => innerResult)` works beautifully to unwrap the nesting. 

Lately I've been experimenting with static combinators to use on collections of Option/Result types. Some might be included, but things like going from `Array<Option<T>>` to `Option<Array<T>>` and likewise with result.

Making validator type functions using result has been beautifully composable. Here's a couple pieces of how I can compose a password validator for signup and get the correct error message for what failed to bubble up to the caller:

```ts
/**
 * Given a plaintext password string, returns `Ok(string)`
 * if that password meets requirements or `Err(string)`
 */
export function asPassword(plaintext: string): Result<string, string> {
	return Ok(plaintext)
		.and_then(asTrimmed)
		.and_then(withMinLength(6))
		.and_then(withMaxByteLength(72))
		.and_then(asPrintableChars)
		.map_err((err: string) => {
			// Don't leak passwords on failed attempts
			// the ':' denotes the start of showing the error data
			if (err.includes(':')) {
				return err.slice(0, err.indexOf(':'));
			}

			return err;
		});
}

export function asTrimmed(s: string): Result<string, string> {
	if (s.trim() !== s) {
		return Err(`text contains untrimmed whitespace: '${s}'`);
	}

	return Ok(s);
}

export function withMinLength(min: number): Validator<string> {
	return function asMinLength(s) {
		if (s.length < min) {
			return Err(`the length must be at least ${min}: found ${s.length}`);
		}

		return Ok(s);
	};
}
```

**Comment by cjhoward92** [comment]
That's a nice example, dude. It might be a good one for the README, or for an example if you don't already have it there. `and_then` is really powerful and I'm not sure many people will realize that until they see how it can be used.

As for the convenience function, maybe

`Option.of(maybeArray).mapEach(elem => elem.toLowerCase());`

would make sense some day where it will map the array if the result is `Some<Array<T>>` or return `None` otherwise.

I don't know, just a thought but like you said it doesn't add a lot of value, it's just convenient.

Cool library, though.

I am going to close this. We can chat more on AZ WebDevs if you ever want to discuss more.
